name: test
on:
  issues:
    types: [opened]

jobs:
  read_ticket:
    runs-on: ubuntu-latest
    outputs:
      issue_title: ${{ steps.set_output.outputs.issue_title }}
      issue_body: ${{ steps.set_output.outputs.issue_body }}
    steps:
      - id: set_output
      - name: Get Issue Content
        run: |
          echo "issue_title=${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
          echo "issue_body=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
