name: Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Cache virtualenv
        id: cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Setup virtualenv and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

  formatting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Formatter Check
        run: |
          source .venv/bin/activate
          black --check src/ tests/

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Linter
        run: |
          source .venv/bin/activate
          ruff check src/ tests/

  type_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Type Check
        run: |
          source .venv/bin/activate
          mypy --strict --explicit-package-bases --ignore-missing-imports src/ tests/

  security_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Security Check
        run: |
          source .venv/bin/activate
          # The B101 test (assert usage) is skipped because assert statements are allowed in test code
          # and are not used in production code. This exclusion is intentional and does not compromise security.
          bandit -r src/ tests/ --skip B101

  complexity_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Complexity Check
        run: |
          source .venv/bin/activate
          echo "Cyclomatic Complexity:"
          radon cc src/ tests/ --total-average
          echo "Maintainability Index:"
          radon mi src/ tests/

  testing:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Pytest
        run: |
          source .venv/bin/activate
          pytest --maxfail=3 --disable-warnings -q
