name: Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Cache virtualenv
        id: cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Setup virtualenv and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

  formatting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Formatter Check
        run: |
          source .venv/bin/activate
          black --check .

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Linter
        run: |
          source .venv/bin/activate
          ruff check .

  type_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Type Check
        run: |
          source .venv/bin/activate
          mypy .

  security_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Security Check
        run: |
          source .venv/bin/activate
          bandit -r .

  complexity_check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Run Complexity Check
        run: |
          source .venv/bin/activate
          echo "Cyclomatic Complexity:"
          radon cc . --total-average
          echo "Maintainability Index:"
          radon mi .
